const { _electron } = require('playwright')
;(async () => {
  const dir = '/tmp/yd-verify-getapp-' + Date.now()
  const app = await _electron.launch({ args: ['.', '--user-data-dir=' + dir] })
  const win = await app.firstWindow()
  await win.waitForSelector('.auth-card', { timeout: 30000 })
  await win.waitForSelector('.auth-get-app', { timeout: 15000 })
  console.log('GET_APP_TEXT=' + (await win.textContent('.auth-get-app')))
  console.log('ICON=' + (await win.$eval('.brand-mark--link', el => el.tagName + '|' + el.title)))
  await new Promise(r => setTimeout(r, 800))
  await win.screenshot({ path: '/Users/zyc/Desktop/砚都跨境/tmp-verify/47-getapp-link.png' })
  await win.click('.auth-get-app')
  await new Promise(r => setTimeout(r, 1500))
  console.log('CLICK_OK')
  await app.close()
  process.exit(0)
})().catch(e => { console.error('ERR', e.message); process.exit(1) })
